- route: /default/test
  verb: GET
  render_method: html #html, js, text
  file_controller: default_test/GET_default_test_controller.cpp
  layout: application.html

- route: /default/test
  verb: POST
  render_method: js #html, js, text
  file_controller: default_test/POST_default_test_controller.cpp
  layout: null